language: go

os:
  - linux

dist: trusty
sudo: required

go:
  - 1.8.x

script:
  - go test -v ./...

before_install:
  - sudo apt-get install libusb-dev libusb-1.0-0 libusb-1.0-0-dev
  - go env && pwd
